export enum CardValuesEnum {
  aceOfSpades = 'Ace of Spades',
  twoOfSpades = '2 of Spades',
  threeOfSpades = '3 of Spades',
  fourOfSpades = '4 of Spades',
  fiveOfSpades = '5 of Spades',
  sixOfSpades = '6 of Spades',
  sevenOfSpades = '7 of Spades',
  eightOfSpades = '8 of Spades',
  nineOfSpades = '9 of Spades',
  tenOfSpades = '10 of Spades',
  jackOfSpades = 'Jack of Spades',
  queenOfSpades = 'Queen of Spades',
  kingOfSpades = 'King of Spades',

  aceOfHearts = 'Ace of Hearts',
  twoOfHearts = '2 of Hearts',
  threeOfHearts = '3 of Hearts',
  fourOfHearts = '4 of Hearts',
  fiveOfHearts = '5 of Hearts',
  sixOfHearts = '6 of Hearts',
  sevenOfHearts = '7 of Hearts',
  eightOfHearts = '8 of Hearts',
  nineOfHearts = '9 of Hearts',
  tenOfHearts = '10 of Hearts',
  jackOfHearts = 'Jack of Hearts',
  queenOfHearts = 'Queen of Hearts',
  kingOfHearts = 'King of Hearts',

  aceOfDiamonds = 'Ace of Diamonds',
  twoOfDiamonds = '2 of Diamonds',
  threeOfDiamonds = '3 of Diamonds',
  fourOfDiamonds = '4 of Diamonds',
  fiveOfDiamonds = '5 of Diamonds',
  sixOfDiamonds = '6 of Diamonds',
  sevenOfDiamonds = '7 of Diamonds',
  eightOfDiamonds = '8 of Diamonds',
  nineOfDiamonds = '9 of Diamonds',
  tenOfDiamonds = '10 of Diamonds',
  jackOfDiamonds = 'Jack of Diamonds',
  queenOfDiamonds = 'Queen of Diamonds',
  kingOfDiamonds = 'King of Diamonds',

  aceOfClubs = 'Ace of Clubs',
  twoOfClubs = '2 of Clubs',
  threeOfClubs = '3 of Clubs',
  fourOfClubs = '4 of Clubs',
  fiveOfClubs = '5 of Clubs',
  sixOfClubs = '6 of Clubs',
  sevenOfClubs = '7 of Clubs',
  eightOfClubs = '8 of Clubs',
  nineOfClubs = '9 of Clubs',
  tenOfClubs = '10 of Clubs',
  jackOfClubs = 'Jack of Clubs',
  queenOfClubs = 'Queen of Clubs',
  kingOfClubs = 'King of Clubs',
}
